import type { ProjectBrief } from '../schema';
import { hasAiTool } from '../aiTools';
import { formatOwner } from '../templateDisplay';

export function generateActiveContext(brief: ProjectBrief): string {
  const { project } = brief;
  const now = new Date().toISOString().split('T')[0];
  const currentPhase = brief.workflow.phases_count === 1 ? 'Phase 0 — Project Initialization' : 'Phase 1 — Planning';
  const currentWork = brief.workflow.phases_count === 1
    ? 'Phase 0 execution has started. Turn the generated starter into a concrete first delivery.'
    : 'Phase 1 planning is in progress. Convert generated docs into concrete requirements, architecture, and first tasks.';
  const toolFiles = [
    '`PROJECT.md`',
    hasAiTool(brief.tech, 'claude_code') ? '`CLAUDE.md`' : null,
    hasAiTool(brief.tech, 'gemini_cli') ? '`GEMINI.md`' : null,
  ].filter(Boolean).join('\n- ');

  return `# ACTIVE_CONTEXT.md — Current Project State

## Last Updated
${now}

## Current Phase
${currentPhase}

## What Has Been Done
- Project structure generated by RepoGenesis.
- Common constitution created in PROJECT.md.
- Tool-specific wrapper files created when enabled.
- Documentation templates created.

## What Is Being Done Now
- ${currentWork}

## What Is Blocked
- No technical blockers detected at generation time.
- Product scope may still contain TBD items that should be resolved during planning.

## Key Decisions Made
- Project initialized: ${project.name} (${project.slug})
- Owner: ${formatOwner(project.owner)}

## Files That Exist
- ${toolFiles}
- \`docs/ACTIVE_CONTEXT.md\` (this file)
- \`docs/REQUIREMENTS.md\`
- \`docs/ARCHITECTURE.md\`
- \`docs/ROADMAP.md\`
- \`docs/ADR/0000-template.md\`
- \`docs/runbooks/README.md\`
- \`docs/runbooks/skill-install.md\`
- \`plans/template.md\`
- \`prompts/restart.md\`
- \`SECURITY.md\`
- \`.env.example\`
- \`.gitignore\`
- \`skills/README.md\`
- \`repogenesis.skills.json\`
- \`.repogenesis/manifest.json\`

## Next Step
Turn the generated docs into concrete Phase 1 decisions before starting implementation.
`;
}
