import type { ProjectBrief } from '../schema';

export function generateActiveContext(brief: ProjectBrief): string {
  const { project } = brief;
  const now = new Date().toISOString().split('T')[0];

  return `# ACTIVE_CONTEXT.md — Current Project State

## Last Updated
${now}

## Current Phase
Phase 0 — Project Initialization

## What Has Been Done
- Project structure generated by RepoGenesis.
- claude.md (constitution) created.
- Documentation templates created.

## What Is Being Done Now
- Phase 0 complete. Ready for Phase 1 planning.

## What Is Blocked
- Nothing currently blocked.

## Key Decisions Made
- Project initialized: ${project.name} (${project.slug})
- Owner: ${project.owner}

## Files That Exist
- \`claude.md\`
- \`docs/ACTIVE_CONTEXT.md\` (this file)
- \`docs/REQUIREMENTS.md\`
- \`docs/ARCHITECTURE.md\`
- \`docs/ROADMAP.md\`
- \`docs/ADR/0000-template.md\`
- \`plans/template.md\`
- \`prompts/restart.md\`
- \`SECURITY.md\`
- \`.env.example\`
- \`.gitignore\`

## Next Step
Begin Phase 1 planning.
`;
}
